x=10
try:
    print(x)
except:
    print("Try Again")

print("Outside run")